# Generated by Django 4.2.3 on 2023-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.TimeField(default='00:02:00', verbose_name='время на выполнение привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='время'),
        ),
    ]
